app:
  log_level: ${LOG_LEVEL:-INFO}
  input_path: ${INPUT_FILE:-./input}
  output_dir: ${OUTPUT_PATH:-./output}
  input_file_type: ${INPUT_FILE_TYPE:-auto}
  input_mode: ${INPUT_MODE:-batch}
  input_file: ${INPUT_TARGET_FILE:-}
  outdoor_temp_humidity_file: ${OUTDOOR_TEMP_HUMIDITY_FILE:-}
  range_start: ${RANGE_START:-}
  range_end: ${RANGE_END:-}
  max_span_days: ${MAX_SPAN_DAYS:-}
  highlight_start_time: ${HIGHLIGHT_START_TIME:-}
  highlight_end_time: ${HIGHLIGHT_END_TIME:-}
  plot_format: ${PLOT_FORMAT:-png}
